name: "Run CI tests using tox"
inputs:
  python:
    required: true
runs:
  using: "composite"
  steps:
  - name: run CI tests
    run: tox run -e${INPUTS_PYTHON}-ci-action
    shell: bash
    env:
      INPUTS_PYTHON: ${{ inputs.python }}
