name: "Preflight checks for Lint"
inputs:
  lint_paths:
    required: true
outputs:
  need_lint:
    value: ${{ steps.paths.outputs.paths == 'true' }}
runs:
  using: "composite"
  steps:
  - id: paths
    uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
    with:
      filters: ${{ inputs.lint_paths }}
