name: "Publish to Ansible Galaxy using tox"
inputs:
  galaxy_token:
    required: true
  tag:
    required: true
runs:
  using: "composite"
  steps:
  - name: publish collection
    run: tox run -e publish-action
    shell: bash
    env:
      ANSIBLE_GALAXY_TOKEN: ${{ inputs.galaxy_token }}
      TAG: ${{ inputs.tag }}
