name: "Build CI image"
inputs:
  base_image:
    required: true
  image_name:
    required: true
  image_registry:
    required: true
  registry_username:
    required: true
  registry_password:
    required: true
  hash_files:
    required: true
  build_args:
    required: false
runs:
  using: "composite"
  steps:
  - name: check cache for previous image builds
    id: imagefiles
    uses: actions/cache@v3
    with:
      path: workflow-support/make_ci_image.sh
      key: ${{ github.ref_name }}-${{ hashfiles(inputs.hash_files) }}
  - name: build image
    if: (steps.imagefiles.outputs.cache-hit != 'true') || (github.event_name == 'schedule')
    run: workflow-support/make_ci_image.sh ${{ inputs.base_image }} ${{ inputs.image_name }} ${{ inputs.build_args }}
    shell: bash
  - name: login to registry
    if: (steps.imagefiles.outputs.cache-hit != 'true') || (github.event_name == 'schedule')
    run: buildah login -u="${{ inputs.registry_username }}" -p="${{ inputs.registry_password }}" ${{ inputs.image_registry }}
    shell: bash
  - name: publish image to registry
    if: (steps.imagefiles.outputs.cache-hit != 'true') || (github.event_name == 'schedule')
    run: buildah push ${{ inputs.image_name }}
    shell: bash
