name: "Make CI Image"
inputs:
  base_image:
    required: true
  image_name:
    required: true
  image_cache_key:
    required: true
  image_registry:
    required: true
  registry_username:
    required: true
  registry_password:
    required: true
  build_args:
    required: false
runs:
  using: "composite"
  steps:
  - name: build image
    run: workflow-support/make_ci_image.sh ${INPUTS_BASE_IMAGE} ${INPUTS_IMAGE_NAME} ${INPUTS_BUILD_ARGS}
    shell: bash
    env:
      INPUTS_BASE_IMAGE: ${{ inputs.base_image }}
      INPUTS_IMAGE_NAME: ${{ inputs.image_name }}
      INPUTS_BUILD_ARGS: ${{ inputs.build_args }}
  - name: login to registry
    run: buildah login -u="${INPUTS_REGISTRY_USERNAME}" -p="${INPUTS_REGISTRY_PASSWORD}" ${INPUTS_IMAGE_REGISTRY}
    shell: bash
    env:
      INPUTS_REGISTRY_USERNAME: ${{ inputs.registry_username }}
      INPUTS_REGISTRY_PASSWORD: ${{ inputs.registry_password }}
      INPUTS_IMAGE_REGISTRY: ${{ inputs.image_registry }}
  - name: publish image to registry
    run: buildah push ${INPUTS_IMAGE_NAME}
    shell: bash
    env:
      INPUTS_IMAGE_NAME: ${{ inputs.image_name }}
  - name: record image key in cache
    uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
    with:
      path: workflow-support/make_ci_image.sh
      key: ${{ inputs.image_cache_key }}
