name: "Make CI Image"
inputs:
  base_image:
    required: true
  image_name:
    required: true
  image_cache_key:
    required: true
  image_registry:
    required: true
  registry_username:
    required: true
  registry_password:
    required: true
  build_args:
    required: false
runs:
  using: "composite"
  steps:
  - name: build image
    run: workflow-support/make_ci_image.sh ${{ inputs.base_image }} ${{ inputs.image_name }} ${{ inputs.build_args }}
    shell: bash
  - name: login to registry
    run: buildah login -u="${{ inputs.registry_username }}" -p="${{ inputs.registry_password }}" ${{ inputs.image_registry }}
    shell: bash
  - name: publish image to registry
    run: buildah push ${{ inputs.image_name }}
    shell: bash
  - name: record image key in cache
    uses: actions/cache/save@v3
    with:
      path: workflow-support/make_ci_image.sh
      key: ${{ inputs.image_cache_key }}
