name: "Preflight checks for CI"
outputs:
  need_image:
    value: ${{ (steps.skip_check.outputs.image_files == 'true') || (github.event_name == 'schedule') }}
  image_tag:
    value: ${{ steps.main.outputs.image_tag }}${{ steps.pr.outputs.image_tag }}
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - id: skip_check
    uses: dorny/paths-filter@v2
    with:
      filters: workflow-support/image_files.yml
    if: github.event_name != 'schedule'
  - id: main
    run: echo "name=image_tag::main" >> $GITHUB_OUTPUT
    shell: bash
    if: (github.event_name != 'pull_request') || (steps.skip_check.outputs.image_files != 'true')
  - id: pr
    run: echo "name=image_tag::pr${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
    shell: bash
    if: (github.event_name == 'pull_request') && (steps.skip_check.outputs.image_files == 'true')
