name: CI

on:
  push:
    branches:
    - main

jobs:
  preflight:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - id: get_versions
      run: cat workflow-support/pdns-versions.json >> $GITHUB_OUTPUT
      shell: bash
    - run: echo ${{ fromJSON(steps.get_versions.outputs.versions).pdns }}
      shell: bash
  ci-image:
    runs-on: ubuntu-20.04
    needs:
    - preflight
    strategy:
      matrix:
        pdns: ${{ needs.preflight.outputs.versions }}
    steps:
    - run: echo ${{ matrix.pdns }}
      shell: bash
